name: Build and deploy Node.js app to Azure Web App - echoverse

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          # Optional: Remove if no build step is required
          npm run build --if-present
          # Optional: Remove if no tests are available
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9EF77BDDBD8B428F81721215240F63EE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C2DD86CA2C841CB9135A519A7FF62B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D748B74A9A2F4180955131A8D25C61BB }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'echoverse'  # Replace with your actual app name
          slot-name: 'Production'  # This is optional if you don’t use deployment slots
          package: .  # Deploy the current directory

      # Optional: Check if deployment was successful
      - name: Check Azure Web App Logs
        run: az webapp log tail --name echoverse --resource-group <resource-group-name>
